### ISSUE TITLE
Progress Bar stays at 0 percent on python 3.10

### ISSUE THREAD

**Issue by landerson78** [ilstam/FF-Multi-Converter#65]
after update to python 3 3.10 on arch the progress bar stays at 0 even tho it seems to work but wont go to a 2nd file if u que up more than 1 file.

**Comment by Csokis** [comment]
Exactly! :(

Here is the error:

`Exception in thread Thread-1 (convert):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/ffmulticonverter/progress.py", line 249, in convert
    if conv_func(*params):
  File "/usr/lib/python3.10/site-packages/ffmulticonverter/progress.py", line 307, in convert_video
    self.nowQPBar.setValue(100 * now_sec / total)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'`

**Comment by ilstam** [comment]
Hi,

I pushed a change that hopefully fixes that for you: c47d47ab7f66a1973b1314ef531de2fb444c2fe6

You can download the latest code from github and launch the program using the launcher script included:
`./FF-Multi-Converter/launcher`

Hope that helps.

**Comment by Csokis** [comment]
Works perfectly! :+1: 

Thank you very much! :smiling_face_with_three_hearts:

**Comment by landerson78** [comment]
ty for your hard work it is working with this one
